// 自动批量生成草稿：从待审选题池获取高置信度选题，自动生成草稿。
// 用于定时任务或手动触发，减少人工干预。

import type { FactsBlock } from "@51guapi/shared";
import { listPendingTopics } from "./pending-store.js";

export interface AutoGenerateOptions {
	/** 最低置信度（默认 0.5）。 */
	minConfidence?: number;
	/** 单次最多生成数（默认 5）。 */
	maxItems?: number;
}

export interface AutoGenerateResult {
	/** 成功生成的草稿数。 */
	generated: number;
	/** 跳过的选题数（置信度不足等）。 */
	skipped: number;
	/** 出错数。 */
	errors: number;
	/** 生成的草稿列表。 */
	drafts: Array<{
		topicId: string;
		title: string;
		facts: FactsBlock; // ACG-only pipeline
	}>;
}

/**
 * 自动批量生成草稿。
 * 从 pending_topics 表获取高置信度选题，返回可直接用于生成草稿的数据。
 * 注意：此函数只做数据准备，LLM 调用由调用方完成。
 */
export async function autoGenerateDrafts(
	opts: AutoGenerateOptions = {},
): Promise<AutoGenerateResult> {
	const { minConfidence = 0.5, maxItems = 5 } = opts;

	const result: AutoGenerateResult = {
		generated: 0,
		skipped: 0,
		errors: 0,
		drafts: [],
	};

	// 獲取 ACG 待審選題（按置信度降序，domain='acg' 避免混入 gossip 選題）
	const topics = await listPendingTopics(
		maxItems * 2,
		"pending",
		"score",
		"acg",
	);

	// 筛选符合置信度的选题，并记录跳过数，再截断到 maxItems
	const passing = topics.filter((t) => t.confidence >= minConfidence);
	result.skipped = topics.length - passing.length;
	const validTopics = passing.slice(0, maxItems);

	// 组装结果
	for (const topic of validTopics) {
		if (result.generated >= maxItems) break;
		result.drafts.push({
			topicId: topic.id,
			title: topic.title,
			facts: topic.facts as FactsBlock,
		});
		result.generated++;
	}

	return result;
}
