/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as GossipRankRouteImport } from './routes/gossip-rank'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as IndexRouteImport } from './routes/index'

const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const GossipRankRoute = GossipRankRouteImport.update({
  id: '/gossip-rank',
  path: '/gossip-rank',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/draft': typeof DraftRoute
  '/gossip-rank': typeof GossipRankRoute
  '/metrics': typeof MetricsRoute
  '/pending': typeof PendingRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/draft': typeof DraftRoute
  '/gossip-rank': typeof GossipRankRoute
  '/metrics': typeof MetricsRoute
  '/pending': typeof PendingRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/draft': typeof DraftRoute
  '/gossip-rank': typeof GossipRankRoute
  '/metrics': typeof MetricsRoute
  '/pending': typeof PendingRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/draft'
    | '/gossip-rank'
    | '/metrics'
    | '/pending'
    | '/settings'
    | '/sites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/draft'
    | '/gossip-rank'
    | '/metrics'
    | '/pending'
    | '/settings'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/draft'
    | '/gossip-rank'
    | '/metrics'
    | '/pending'
    | '/settings'
    | '/sites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  DraftRoute: typeof DraftRoute
  GossipRankRoute: typeof GossipRankRoute
  MetricsRoute: typeof MetricsRoute
  PendingRoute: typeof PendingRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gossip-rank': {
      id: '/gossip-rank'
      path: '/gossip-rank'
      fullPath: '/gossip-rank'
      preLoaderRoute: typeof GossipRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  DraftRoute: DraftRoute,
  GossipRankRoute: GossipRankRoute,
  MetricsRoute: MetricsRoute,
  PendingRoute: PendingRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
